#######################################################################################
# Book settings
title : PseudoLab Tutorial Book
author: PseudoLab Tutorial Team
logo: 'PseudoLab_logo.png'

# Information about where the book exists on the web
description: >-
  A tutorial book on applying deep learning to solve daily life problems.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off #cache for default setting
  allow_errors                : true

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/Pseudo-Lab/Tutorial-Book
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
exclude_patterns: [draft/*]